BBBBBBB BBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
    XXX XX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBB
    XXXXXXX XXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XX
    XXXXXXX
BBBBBBBB BBBBBBB