BBBBBBB BBBBBBBBBBBB

BBBBB BBBBBBBBBB
    XXX XXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBB
    XXXXXXX XXXXXXXX
    XXXXXXX XXX XXXX XXX XXXX XX XXXXXXXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XX
    XXXXXXX
BBBBBBBB BBBBBBB