BBBBBBB BBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
    XXXX XX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBB
    XXXXXXXX XXXXXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX
    XXXXXXX
BBBBBBBB BBBBBBB