BBBB BBBBBBB
BBBBBBBBBBBB BBBB BB BBBBBBBBBBBB
BBBB BBBB
BBBBBBBBBB BBB
 gettext(u'\n\nHello from %(site_name)s.\n\n%(user_display)s\nIf you requested this email please click on the link below:\n%(activate_url)s\n\n') 

SSSSS SSSS SSSSSSSSSSSSSS

SSSSSSSSSSSSSSSS
SS SSS SSSSSSSSS SSSS SSSSS SSSSSS SSSSS SS SSS SSSS SSSSSS
SSSSSSSSSSSSSSSS


BBBBBBBBBBBBB